import{a as L,S as w}from"./assets/vendor-BHxofHDG.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&a(d)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const b="https://pixabay.com/api/",S="46110623-cffeede45492ee1adb33fe3c4",f=15;async function h(t,s=1){const r=new URLSearchParams({key:S,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:s,per_page:f}),a=`${b}?${r}`;try{const e=await L.get(a);return console.log("fetchImages data:",e.data),e.data}catch(e){console.error("Error fetching images:",e)}}function m(t){return t.reduce((s,r)=>s+`<article class="gallery-item">
                <a href="${r.largeImageURL}" class="gallery-link">
                    <img src="${r.webformatURL}" alt="${r.tags}" class="gallery-image" />
                </a>
                <ul class="info">
                    <li class="info-item"><strong>Likes:</strong> ${r.likes}</li>
                    <li class="info-item"><strong>Views:</strong> ${r.views}</li>
                    <li class="info-item"><strong>Comments:</strong> ${r.comments}</li>
                    <li class="info-item"><strong>Downloads:</strong> ${r.downloads}</li>
                </ul>
            </article>`,"")}const E=document.querySelector(".search-form"),c=document.querySelector(".gallery"),i=document.querySelector(".js-load-more"),u=document.querySelector(".message");let n=1,l=null,g=0;E.addEventListener("submit",v);i.addEventListener("click",M);let y=new w(".gallery a",{captionsData:"alt",captionDelay:250});async function v(t){t.preventDefault();const s=t.currentTarget;if(l=s.elements.query.value.trim(),!!l){n=1;try{const r=await h(l,n);if(g=Math.ceil(r.totalHits/f),console.log("handleSubmit:",r),r.totalHits===0){p("Sorry, there are no images matching your search query. Please try again!"),c.innerHTML="",i.classList.add("is-hidden");return}const a=m(r.hits);c.innerHTML=a,y.refresh(),r.totalHits>n*f?i.classList.remove("is-hidden"):i.classList.add("is-hidden")}catch(r){console.error("Error:",r)}finally{s.reset()}}}async function M(){n+=1,console.log(g);try{const t=await h(l,n);if(console.log("handleLoadMore:",t),t.totalHits===0){p("Sorry, there are no images matching your search query. Please try again!");return}const s=m(t.hits);c.insertAdjacentHTML("beforeend",s),y.refresh(),P(),n>=g&&(i.classList.add("is-hidden"),console.log("We're sorry, but you've reached the end of search results."))}catch(t){console.error("Error:",t)}}function p(t){u.textContent=t,u.classList.remove("is-hidden"),setTimeout(()=>{u.classList.add("is-hidden")},3e3)}function P(){const t=c.lastElementChild;if(t){const s=t.getBoundingClientRect().height;window.scrollBy({top:s*2,left:0,behavior:"smooth"})}else console.error("Were sorry, but you have reached the end of search results.")}
//# sourceMappingURL=index.js.map
