import{a as h}from"./assets/vendor-Cn2Vr82J.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();const y="https://pixabay.com/api/",p="46110623-cffeede45492ee1adb33fe3c4",d=6;async function g(t,o=1){const r=new URLSearchParams({key:p,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:o,per_page:d}),n=`${y}?${r}`;try{const e=await h.get(n);return console.log("fetchImages data:",e.data),e.data}catch(e){console.error("Error fetching images:",e)}}function m(t){return t.reduce((o,r)=>o+`<article class="gallery-item">
                <a href="${r.largeImageURL}" class="gallery-link">
                    <img src="${r.webformatURL}" alt="${r.tags}" class="gallery-image" />
                </a>
                <ul class="info">
                    <li class="info-item"><strong>Likes:</strong> ${r.likes}</li>
                    <li class="info-item"><strong>Views:</strong> ${r.views}</li>
                    <li class="info-item"><strong>Comments:</strong> ${r.comments}</li>
                    <li class="info-item"><strong>Downloads:</strong> ${r.downloads}</li>
                </ul>
            </article>`,"")}const L=document.querySelector(".search-form"),f=document.querySelector(".gallery"),c=document.querySelector(".js-load-more");let a=1,l=null,u=0;L.addEventListener("submit",b);c.addEventListener("click",w);async function b(t){t.preventDefault();const o=t.currentTarget;if(l=o.elements.query.value.trim(),!!l){a=1;try{const r=await g(l,a);u=Math.ceil(r.totalHits/d),console.log("handleSubmit:",r);const n=m(r.hits);f.innerHTML=n,r.totalHits>a*d?c.classList.remove("is-hidden"):c.classList.add("is-hidden")}catch(r){console.error("Error:",r)}finally{o.reset()}}}async function w(){a+=1,console.log(u);try{const t=await g(l,a);console.log("handleLoadMore:",t);const o=m(t.hits);f.insertAdjacentHTML("beforeend",o),E(),a>=u&&(c.classList.add("is-hidden"),console.log("We're sorry, but you've reached the end of search results."))}catch(t){console.error("Error:",t)}}function E(){const t=f.lastElementChild;if(t){const o=t.getBoundingClientRect().height;window.scrollBy({top:o*2,left:0,behavior:"smooth"})}else console.error("Were sorry, but you have reached the end of search results.")}
//# sourceMappingURL=index.js.map
